<?php $this->headTitle($this->translate('Frequently asked questions')) ?>
<h1 id="faqTitle"><?php echo $this->translate('Frequently asked questions') ?></h1>

<h2><a name="what_is_wingz">What is wingz ?</a></h2>
<p>Wingz is demo application based on <a href="http://framework.zend.com"
title="Zend Framework" rel="nofollow">Zend Framework</a>, to expand 
<a href="http://joind.in" title="Joind.in: like the talk, let them know">joind.in</a>'s
features on interacting on conferences and events.</p>
<p>Using the event listing from <a href="http://joind.in"
title="Joind.in: like the talk, let them know">joind.in</a>, you can now share 
your event experiences and comments of the event on your favorite social 
platforms like <a href="http://facebook.com" title="Facebook.com"
rel="nofollow">facebook</a>, <a href="http://twitter.com" title="Twitter.com" 
rel="nofollow">Twitter</a>, <a href="http://linkedin.com" title="Linkedin.com"
rel="nofollow">LinkedIn</a>, <a href="http://gowalla.com" title="Gowalla.com"
rel="nofollow">Gowolla</a> and <a href="http://foursquare.com" title="Foursquare.com"
rel="nofollow">Foursquare</a>.</p>
<p>Wingz is also an open-source project, so you can download the source-code
from <a href="http://github.com/DragonBe/wingz" title="Wingz on Github">GitHub</a>
to see how things are build and use them for your own application development
or dig into the code and learn from it.</p>

<h2><a name="how_can_i_help">How can I help ?</a></h2>
<p>By going to conferences and using this tool you can participate completely
with all that's going on. With an immediate link into <a href="http://joind.in"
title="Joind.in: like the talk, let them know">joind.in</a> you provide
valuable feedback to the speakers and event organizers.</p>
<p>There's a lot of things I haven't thought of, so if you have an idea to
make this idea even better, the code is right there on 
<a href="http://github.com/DragonBe/wingz" title="Wingz on Github">GitHub</a>.
If you find a bug, report the issue on our <a href="http://bugs.wingz.cc"
title="Report an issue on Wingz">bugtracker</a>.</p>