<?php echo $this->doctype() ?>
<html>
    <head>
       <?php 
           echo $this->headMeta();
           echo $this->headTitle();
           echo $this->headLink();
           echo $this->headStyle();
           echo $this->headScript();
           echo $this->JQuery() . PHP_EOL;
       ?>
    </head>
    <body>
        <div id="main">
            <div id="header">
                <div id="navigation">
                    <?php echo $this->navigation()->menu() ?>
                    <span id="logo">
                        <a href="<?php echo $this->url(array (
                            'module' => 'default',
                            'controller' => 'index',
                            'action' => 'index',
                        ), null, true)?>"
                        title="<?php echo $this->translate('__HOME') ?>"><img 
                        src="<?php echo $this->baseUrl('/images/wingz_logo.png') ?>"
                        width="188" height="80" alt="Logo"/></a>
                    </span>
                </div>
                <div class="clear">&nbsp;</div>
            </div>
            
            <div id="promo">
                <div id="teaser">
                    <?php echo $this->render('teaser.phtml')?>
                </div>
            </div>
            
            <div id="center"><?php echo $this->layout()->content; ?></div>
            
            <div id="footer">
                <?php echo $this->render('footer.phtml') ?>
            </div>
        </div>
    </body>
</html>